### ISSUE TITLE
[links] Links for Study and Programming in Perl.

### ISSUE THREAD

**Issue by gungundable** [0xpr1v8/pr1v8society#1]
**- Basic perl:**
https://en.wikipedia.org/wiki/Perl
https://computer.howstuffworks.com/perl.htm

**- I recommend you read the documentation at perl.org:**
https://perldoc.perl.org/5.30.0/index-overview.html

**- This Works like a guide. If you want learn step by step.**
https://www.tutorialspoint.com/perl/perl_study.htm

**- Perl 6 Documentation:**
https://docs.perl6.org/language/5to6-nutshell

**- Math & Perl:**
https://www.math.utah.edu/docs/info/perl_11.html

**Comment by 6f7a79** [comment]
Wiki topic opened :+1: 

. https://github.com/0xpr1v8/pr1v8society/wiki/Perl

**Comment by gungundable** [comment]
**To help those with questions, in my opinion Dave Hodgkinson answer was the best.**

_What are types of projects/applications for which Perl is the best choice of language?_
https://www.quora.com/What-are-types-of-projects-applications-for-which-Perl-is-the-best-choice-of-language
