### ISSUE TITLE
[links] Links para estudar Criptografia.

### ISSUE THREAD

**Issue by gungundable** [0xpr1v8/pr1v8society#2]
**- Introduzindo ao assunto de Criptografia.**
http://www.bosontreinamentos.com.br/seguranca/introducao-a-criptografia/
https://www.oficinadanet.com.br/artigo/443/o_que_e_criptografia
https://pt.wikipedia.org/wiki/Hist%C3%B3ria_da_criptografia
http://www.serafim.eti.br/academia/recursos/Roteiro_04-Criptografia_e_Criptoanalise.pdf
https://www.gta.ufrj.br/grad/07_1/ass-dig/Introduo.html
http://www.matera.com/blog/post/criptografia-hash-assinatura-digital-qual-diferenca

**- “Arsenal” de artigos:**
https://pt.wikipedia.org/wiki/Categoria:Criptografia 

**- Alguns exemplos de cifras:** 
http://www.bosontreinamentos.com.br/seguranca/criptografia-cifra-de-cesar/
http://clubedosgeeks.com.br/sem-categoria/cifra-de-cesar-criptografia-monoalfabetica
http://www.bosontreinamentos.com.br/seguranca/criptografia-cifra-de-vigenere/

**- Diferenças de Cifra de Fluxo e Bloco:**
http://www.serafim.eti.br/academia/recursos/Roteiro_05-Cifras_de_Fluxo_e_Bloco.pdf
https://pt.esdifferent.com/difference-between-stream-cipher-and-block-cipher

**- Criptoanálise:**
http://www.seknet.com.br/criptoanalise.html

**-  Recomendação de video aulas Segurança e Criptografia:**
https://www.youtube.com/watch?v=cWld3rMD7Wk&list=PLucm8g_ezqNred_fII4GzZxMi91PKbney

**- Recomendação de Book para estudo mais aprofundado:**
→ Criptografia e Segurança de Redes

**Comment by 6f7a79** [comment]
Mais um link com material recomendado pelo pessoal do CypherpunksBR

https://yadi.sk/d/6mg447DA3Wg9PW
