### ISSUE TITLE
[links] Front-end Developer (Learn and Study).

### ISSUE THREAD

**Issue by gungundable** [0xpr1v8/pr1v8society#3]
**-What is a front-end develper?**
https://frontendmasters.com/books/front-end-handbook/2018/what-is-a-FD.html

**- HTML & CSS:**
**- Beginners Course->** https://www.bitdegree.org/courses/coding-for-beginners/
**Html->** https://www.w3schools.com/html/default.asp
**Css ->** https://www.w3schools.com/css/default.asp
**Full course ->** https://www.youtube.com/watch?v=mU6anWqZJcc&list=PLWKjhJtqVAbnSe1qUNMG7AbPmjIG54u88
**Curso ->** https://www.youtube.com/watch?v=epDCjksKMok&list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o

**- JAVASCRIPT:**
**Tutorial ->** https://www.w3schools.com/js/default.asp
**Full course ->** https://www.youtube.com/watch?v=PkZNo7MFNFg

**- FRAMEWORKS:**
**Bootstrap ->**
https://www.w3schools.com/bootstrap/bootstrap_ver.asp
**Bootstrap Documentation ->** https://getbootstrap.com/docs/4.1/getting-started/introduction/
**Bulma Documentation ->** https://bulma.io/documentation/

**- GRAPHIC DESIGN:**
_- It isn't obligatory, but you must at least know the basic to create your banners, logos, etc._
**Canva ->** https://www.canva.com/
**Gimp ->** https://www.gimp.org/docs/
**Fireworks ->** https://www.adobe.com/products/fireworks.html

**Comment by 6f7a79** [comment]
Oh! Thank You!

Gonna add a topic for **FrontEnd Dev** @ the [wiki](https://github.com/0xpr1v8/pr1v8society/wiki)

**Comment by 6f7a79** [comment]
Wiki topic created: [Front End](https://github.com/0xpr1v8/pr1v8society/wiki/Front-End)


*link for bootstrap documentation changed to the most recent version;*
  `Bootstrap Documentation - https://getbootstrap.com/docs/4.3/getting-started/introduction/`
