### ISSUE TITLE
[links] Back-End Development 

### ISSUE THREAD

**Issue by KaioGomesx** [0xpr1v8/pr1v8society#4]
**NodeJS** {
url - > https://jornadadodev.com.br/cursos/curso-de-nodejs?utm_source=facebook&utm_campaign=desenvolvimento_web&utm_medium=grupos&utm_content=curso-de-nodejs
url - > https://www.w3schools.com/nodejs/
url - > https://imasters.com.br/back-end/tdd-em-nodejs-conhecendo-o-jest
url - > https://t.me/AcervoHackerBR/1839
url - > https://youtu.be/KKTX1l3sZGk
url - > https://t.me/AcervoHackerBR/2381
url - > https://www.netguru.com/blog/top-companies-used-nodejs-production
url - > https://t.me/acervopr1v8/220
url - > https://t.me/AcervoHackerBR/2129
url - > https://devcenter.heroku.com/articles/getting-started-with-nodejs
url - > https://www.youtube.com/watch?v=MkkbUfcZUZM
url - > https://t.me/AcervoHackerBR/2141
url - > https://zeit.co/examples/nodejs
}

**Ruby** {
url - > https://www.youtube.com/watch?v=z4fCLSeAjcA
url - > https://jornadadodev.com.br/cursos/curso-de-ruby?utm_source=facebook&utm_campaign=desenvolvimento_web&utm_medium=grupos&utm_content=curso-de-ruby
url - > https://jornadadodev.com.br/cursos/curso-de-ruby-rails?utm_source=facebook&utm_campaign=desenvolvimento_web&utm_medium=grupos&utm_content=curso-de-ruby-rails
}

**PHP** {
url - > https://www.youtube.com/playlist?list=PLHz_AreHm4dm4beCCCmW4xwpmLf6EHY9k
url - > https://b7web.com.br/php/
url - > https://t.me/linuxbras/1118
url - > https://t.me/linuxbras/771
url - > https://youtu.be/abpKrDzkR_w
url - > https://t.me/linuxbras/349
url - > https://t.me/AcervoHackerBR/1880
url - > https://t.me/AcervoHackerBR/1777
url - > https://t.me/acervopr1v8/92
}

**Há mais links perdidos por aqui mas por enquanto, peguei os que considero bons**

**Comment by 6f7a79** [comment]
Thank yoou!

**Datalove <3**

**Comment by ghost** [comment]
add umas info e referencia (ex -> link), pra ñ ficar só link jogado

**Comment by 6f7a79** [comment]
> add umas info e referencia (ex -> link), pra ñ ficar só link jogado

Tip: **Add link title to the issue**

**Comment by Kaioba1** [comment]
> add umas info e referencia (ex -> link), pra ñ ficar só link jogado

Done :)

**Comment by gungundable** [comment]
_**Tomei a liberdade de ajeitar os links, adicionei alguns links para esclarecer e limpei os trackers de seus links,  por favor seguir o padrão e não fazer pela metade, agradeço.**_


**NODE.JS**

**Curso de NodeJS - >** https://jornadadodev.com.br/cursos/curso-de-nodejs
**NodeJs Tutorials, Examples, References, Etc. - >** https://www.w3schools.com/nodejs/
**O que é TDD? / NodeJs / Koa.js / Jest - >** https://imasters.com.br/back-end/tdd-em-nodejs-conhecendo-o-jest
**Upload de arquivos: back-end com NodeJS ->** https://www.youtube.com/watch?v=MkkbUfcZUZM
**API NodeJS + Express + Mongo – Autenticação ->**  https://www.youtube.com/watch?v=KKTX1l3sZGk

**-Examples NodeJs:** 
**Example ->** https://zeit.co/examples/nodejs
**12 Top - Applications Written in Node.js ->**
https://www.netguru.com/blog/top-companies-used-nodejs-production

**-Outros Assuntos relacionados a NodeJs:**
**What is Heroku ->** https://en.wikipedia.org/wiki/Heroku
**Getting Started on Heroku with Node.js ->** 
https://devcenter.heroku.com/articles/getting-started-with-nodejs
**Introdução ao TypeScript ->** https://www.devmedia.com.br/introducao-ao-typescript/36729

**-Banco de dados NoSQL:**
**Introdução aos Bancos de dados NoSQL -Tutorial, Conceito, Introdução ->**  https://www.devmedia.com.br/introducao-aos-bancos-de-dados-nosql/26044


**- NodeJs Material para estudo no Telegram:**
**Learning NodeJS – Pdf telegram channel ->** https://t.me/s/AcervoHackerBR/2381
**Ebook NodeJs para Iniciantes - >** https://t.me/AcervoHackerBR/1839
**Curso completo de Desenvolvedor NodeJS e MongoDB - >** https://t.me/acervopr1v8/220
**Banco de dados NoSQL e Introdução ao Mongo DB ->** https://t.me/AcervoHackerBR/2129
**Curso NodeJs, Typescript, ES6 e PostgreSQL ->** https://t.me/AcervoHackerBR/2141


**RUBY**

**Curso de Ruby ->** https://jornadadodev.com.br/cursos/curso-de-ruby
**Curso de Ruby on Rails – Framework ->** https://jornadadodev.com.br/cursos/curso-de-ruby-rails
**Ruby on Rails 01 - Criando um Blog ->** https://www.youtube.com/watch?v=z4fCLSeAjcA


**PHP**

**Curso de PHP para Iniciantes ->** https://youtu.be/F7KzJ7e6EAc
**Php do jeito certo com ou sem um curso de php ->** https://www.youtube.com/watch?v=abpKrDzkR_w

**-Php Material de estudo no Telegram:**

**Apostila de Curso Php e MySql ->** https://t.me/linuxbras/1118
**Curso Php, MySql e Fundamentos da Web ->** https://t.me/linuxbras/771
**Curso Php – Básico ao Avançado ->** https://t.me/linuxbras/349
**Curso Básico  Php e Trabalhando com APIs ->** https://t.me/AcervoHackerBR/1880
**Curso Php 7 – Básico ao Avançado - pdfs->** https://t.me/AcervoHackerBR/1777
**Curso Php 7 – Softblue Completo ->** https://t.me/acervopr1v8/92

**Comment by Kaioba1** [comment]
> _**Tomei a liberdade de ajeitar os links, adicionei alguns links para esclarecer e limpei os trackers de seus links, por favor seguir o padrão e não fazer pela metade, agradeço.**_
> 
> **NODE.JS**
> 
> **Curso de NodeJS - >** https://jornadadodev.com.br/cursos/curso-de-nodejs
> **NodeJs Tutorials, Examples, References, Etc. - >** https://www.w3schools.com/nodejs/
> **O que é TDD? / NodeJs / Koa.js / Jest - >** https://imasters.com.br/back-end/tdd-em-nodejs-conhecendo-o-jest
> **Upload de arquivos: back-end com NodeJS ->** https://www.youtube.com/watch?v=MkkbUfcZUZM
> **API NodeJS + Express + Mongo – Autenticação ->** https://www.youtube.com/watch?v=KKTX1l3sZGk
> 
> **-Examples NodeJs:**
> **Example ->** https://zeit.co/examples/nodejs
> **12 Top - Applications Written in Node.js ->**
> https://www.netguru.com/blog/top-companies-used-nodejs-production
> 
> **-Outros Assuntos relacionados a NodeJs:**
> **What is Heroku ->** https://en.wikipedia.org/wiki/Heroku
> **Getting Started on Heroku with Node.js ->**
> https://devcenter.heroku.com/articles/getting-started-with-nodejs
> **Introdução ao TypeScript ->** https://www.devmedia.com.br/introducao-ao-typescript/36729
> 
> **-Banco de dados NoSQL:**
> **Introdução aos Bancos de dados NoSQL -Tutorial, Conceito, Introdução ->** https://www.devmedia.com.br/introducao-aos-bancos-de-dados-nosql/26044
> 
> **- NodeJs Material para estudo no Telegram:**
> **Learning NodeJS – Pdf telegram channel ->** https://t.me/s/AcervoHackerBR/2381
> **Ebook NodeJs para Iniciantes - >** https://t.me/AcervoHackerBR/1839
> **Curso completo de Desenvolvedor NodeJS e MongoDB - >** https://t.me/acervopr1v8/220
> **Banco de dados NoSQL e Introdução ao Mongo DB ->** https://t.me/AcervoHackerBR/2129
> **Curso NodeJs, Typescript, ES6 e PostgreSQL ->** https://t.me/AcervoHackerBR/2141
> 
> **RUBY**
> 
> **Curso de Ruby ->** https://jornadadodev.com.br/cursos/curso-de-ruby
> **Curso de Ruby on Rails – Framework ->** https://jornadadodev.com.br/cursos/curso-de-ruby-rails
> **Ruby on Rails 01 - Criando um Blog ->** https://www.youtube.com/watch?v=z4fCLSeAjcA
> 
> **PHP**
> 
> **Curso de PHP para Iniciantes ->** https://youtu.be/F7KzJ7e6EAc
> **Php do jeito certo com ou sem um curso de php ->** https://www.youtube.com/watch?v=abpKrDzkR_w
> 
> **-Php Material de estudo no Telegram:**
> 
> **Apostila de Curso Php e MySql ->** https://t.me/linuxbras/1118
> **Curso Php, MySql e Fundamentos da Web ->** https://t.me/linuxbras/771
> **Curso Php – Básico ao Avançado ->** https://t.me/linuxbras/349
> **Curso Básico Php e Trabalhando com APIs ->** https://t.me/AcervoHackerBR/1880
> **Curso Php 7 – Básico ao Avançado - pdfs->** https://t.me/AcervoHackerBR/1777
> **Curso Php 7 – Softblue Completo ->** https://t.me/acervopr1v8/92

Oh, sorry, da próxima nem tento fazer então ^^

**Comment by ghost** [comment]
Why all links are in Portuguese? We should be adding resources in English as well. Also, the best guide of any language is its Docs. So please consider adding official doc links

Edit: also using markdown for link will be more better, 

Like:

[Official Python Docs](https://python.org)

Python 
-> python.org

Obviously the Markdown one gives more information & looks good
