### ISSUE TITLE
Privacidade

### ISSUE THREAD

**Issue by Jul10l1r4** [0xpr1v8/pr1v8society#5]
Mobile => [Mantendo a segurança em comunicações digitais (Parte 1)](https://telegra.ph/Mantendo-a-seguran%C3%A7a-em-comunica%C3%A7%C3%B5es-digitais-Parte-1-07-14)

**Comment by 6f7a79** [comment]
wiki topic created [here](https://github.com/0xpr1v8/pr1v8society/wiki/Privacy)
