### ISSUE TITLE
[links]  Python (Study and Programming). 

### ISSUE THREAD

**Issue by gungundable** [0xpr1v8/pr1v8society#6]
**-Article:**

**Why Learn Python? ->** http://www.bestprogramminglanguagefor.me/why-learn-python

**-Python Tutorials:**

**Beginner, Data and Databases, Web, GUI, Network, Plotting, Advanced, Android,
 Computer Vision, Game, Robotics, etc.->** https://pythonspot.com/

**w3schools.com ->** https://www.w3schools.com/python/default.asp

**-Python Courses in Youtube:**
 

 **Full Course - Python Tutorial for Beginners ->** https://www.youtube.com/watch?v=_uQrJ0TkZlc

 **Curso em video - Python ->** https://youtu.be/S9uPNppGsGo

**-Python Examples:**

**codescracker.com ->** https://codescracker.com/python/program/

**pythonforbeginners.com ->** https://www.pythonforbeginners.com/code-snippets-source-code/python-code-examples/

**Python Chatbot ->** http://ai.intelligentonlinetools.com/ml/python-chatbot-code-example/

**Comment by 6f7a79** [comment]
@gungundable like this @gungundable did

**Comment by ghost** [comment]
Some more resources for Python! 
But I have not arranged them. Admins will have to arrange them + will have to add markdown

Official docs for begginers & pros:
https://docs.python.org/3/

pip for beginners:
http://www.pythonforbeginners.com/basics/python-pip-usage

Awesome python pdf for learning py:
https://automatetheboringstuff.com/

MDN'a guide to Python:
https://developer.mozilla.org/en-US/docs/Learn/Drafts/Python

Practicing python:
http://www.practicepython.org/

https://www.hackerrank.com

https://www.codewars.com/

MDN's guide to django, pythons web framework
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django

Demo projects in django:
https://docs.djangoproject.com/en/1.11/

https://simpleisbetterthancomplex.com/2015/11/23/small-open-source-django-projects-to-get-started.html

Python guide on YouTube, from beginners to advance level. Including ml & data science
https://www.youtube.com/user/sentdex/playlists

Python hacks, articles & tips
https://www.pythonweekly.com/

https://www.realpython.com/

Curated list of awesome python things:
https://github.com/vinta/awesome-python

https://github.com/trananhkma/fucking-awesome-python

Learning on mobile devices:
https://play.google.com/store/apps/details?id=com.sololearn

Free Python ebooks:
https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md#python

Lots of ideas to build py projects:
https://github.com/danistefanovic/build-your-own-x

Data Science with Python:
https://github.com/jakevdp/PythonDataScienceHandbook

Things to do with python, article:
https://realpython.com/what-can-i-do-with-python/

Learning paths for Python, article:
https://realpython.com/learning-paths/

Algorithms in python:
https://github.com/TheAlgorithms/Python

**Comment by 6f7a79** [comment]
Wiki topic created [here](https://github.com/0xpr1v8/pr1v8society/wiki/Python)

Please note that this issue is the one we will use to keep updating and changing the wiki topic
